# ~/.config/yazi/theme.toml
[ui]
background = "#282c34"
foreground = "#dcdfe4"
title = "#61afef"
status = "#61afef"
cursor = "#dcdfe4"
border = "#5c6370"
highlight = "#98c379"
selection = "#e06c75"
marker = "#c678dd"
info = "#56b6c2"
warning = "#e5c07b"
error = "#e06c75"
flag = "#c678dd"
tag = "#98c379"

[filetype]
directory = "#61afef"
symlink = "#c678dd"
executable = "#98c379"
image = "#e5c07b"
audio = "#56b6c2"
video = "#d19a66"
document = "#dcdfe4"
archive = "#be5046"
unknown = "#5c6370"
